plugins {
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    compileOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    compileOnly "org.jetbrains:annotations:24.1.0"
}

sourceSets {
    main {
        java {
            srcDir '../common/src/main/java'
            srcDir '../mixins'
        }
        resources {
            srcDir '../common/src/main/resources'
        }
    }
}
