plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
}

group = project.mod_group
version = project.mod_version

allprojects {
    apply plugin: 'java'

    base {
        archivesName = rootProject.mod_name
    }

    version = "${rootProject.mod_version}-${project.name}"
    group = rootProject.mod_group

    repositories {
        maven {
            name = 'TerraformersMC Maven'
            url = 'https://maven.terraformersmc.com/releases'
        }
        mavenCentral()
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    compileJava {
        options.release = 25
        options.encoding = 'UTF-8'
    }

    processResources {
        def expandedVersion = version
        filesMatching(['fabric.mod.json']) {
            expand 'version': expandedVersion
        }
    }

    jar {
        manifest {
            attributes([
                'Specification-Title'     : rootProject.mod_name,
                'Specification-Vendor'    : 'luavixen',
                'Specification-Version'   : '1',
                'Implementation-Title'    : 'Damage Numbers',
                'Implementation-Version'  : rootProject.mod_version,
                'Implementation-Vendor'   : 'luavixen',
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
            ])
        }
    }
}

tasks.named('jar') {
    enabled = false
}
